# Generated by Django 4.0.4 on 2022-05-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='address',
            new_name='country',
        ),
        migrations.AddField(
            model_name='shipping',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipping',
            name='save_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_method',
            field=models.CharField(choices=[('S', 'Standard'), ('E', 'Express')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='street_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='use_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='postcode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
