# Generated by Django 4.0.3 on 2022-05-11 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_orderitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
    ]
