# Generated by Django 4.0.4 on 2022-05-12 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_address_shipping_country_shipping_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='default',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='save_info',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='use_default',
        ),
    ]
