# Generated by Django 4.0.3 on 2022-05-11 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_payment_name_on_card'),
        ('main', '0008_remove_orderitem_customer'),
    ]

    operations = [
    ]
