# Generated by Django 4.0.4 on 2022-05-12 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_shipping_default_remove_shipping_save_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='order',
            new_name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='shippings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.shipping'),
        ),
    ]
