# Generated by Django 4.0.4 on 2022-05-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_order_shipping_orders_order_shippings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='tracking_number',
        ),
    ]
