# Generated by Django 4.0.4 on 2022-05-12 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_merge_20220511_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='address',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipping',
            name='shipping_method',
            field=models.CharField(choices=[('S', 'Standard'), ('E', 'Express')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='street_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='postcode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
