# Generated by Django 4.0.4 on 2022-05-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_address_shipping_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('S', 'Savings'), ('C', 'Cheque')], max_length=2, null=True),
        ),
    ]
