# Generated by Django 4.0.4 on 2022-05-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_shipping_tracking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='orders',
        ),
    ]
