# Generated by Django 4.0.3 on 2022-05-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_address_shipping_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
